### ISSUE TITLE
Undefined rule declaration-property-unit-disallowed-list

### ISSUE THREAD

**Issue by TheSonOfThomp** [hex-ci/vscode-stylelint-plus#26]
Recently the term `blacklist` was updated to `disallowed-list` in stylelint. However it doesn't look like this plugin has been updated to match. VS Code keeps showing the error `Undefined rule declaration-property-unit-disallowed-list` 
![Screen Shot 2020-11-20 at 11 44 27 AM](https://user-images.githubusercontent.com/2414030/99826124-ee7ebe00-2b25-11eb-8bdf-a09e033cd8ea.png)

**Comment by martinschayna** [comment]
Similar problem:

![Screenshot_609](https://user-images.githubusercontent.com/1617977/106051141-58987e00-60e8-11eb-8de7-fd0b259314cc.png)

I have tried to use useLocal option but I have Lerna-based monorepo project and the extension looks for stylelint binary in a wrong folder, instead of project root folder `project/node_modules` it tries to use random sub-module folder `project/packages/module/node_modules`

![Screenshot_612](https://user-images.githubusercontent.com/1617977/106052186-94801300-60e9-11eb-9e0b-d22e39816ef4.png)
